/* fs/buffer.c */

#include <linux/fs.h>

// end is generated by ld, meaning the end of kernel.
extern int end;
struct buffer_head * start_buffer = (struct buffer_head*)&end;
struct buffer_head * hash_table[NR_HASH];

/*
 * Reads a specified block and returns the buffer that contains it.
 * It returns NULL if the block was unreadble.
 *
 * dev - device no.
 * block - block no.
 */
struct buffer_head *bread(int dev, int block) {
}

void buffer_init(long buffer_end) {
	struct buffer_head *h = start_buffer;
	void *b;

	// 640K-1M is used by video memory and BIOS
	if (buffer_end <= 1<<20)
		b = (void*)(640*1024);
	else
		b = (void*)buffer_end;

	// (b-BLOCK_SIZE) is the start of data block, (h+1) is the end of buffer head
	while ((b -= BLOCK_SIZE) )
	
}
